apiVersion: v1
data:
  getnumberofworkers: |
    export APISERVER=https://kubernetes.default.svc
    export SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    export NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    export TOKEN=$(cat ${SERVICEACCOUNT}/token)
    export CACERT=${SERVICEACCOUNT}/ca.crt
    curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/apis/machineconfiguration.openshift.io/v1/machineconfigpools/woker|grep machineCount
kind: ConfigMap
metadata:
  name: getnumberofworkers
  namespace: query-api
