kind: Deployment
apiVersion: apps/v1
metadata:
  name: query-api  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: query-api
        deploymentconfig: query-api
      annotations:
    spec:
      containers:
        - name: query-api
          image: registry.access.redhat.com/ubi8/ubi-minimal:8.8-1014
          command:
            - sleep
            - infinity
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
          - name: APISERVER
            value: "https://kubernetes.default.svc"
          - name: SERVICEACCOUNT
            value: "/var/run/secrets/kubernetes.io/serviceaccount"
          - name: NAMESPACE
            value: "$(cat ${SERVICEACCOUNT}/namespace)"
          - name: TOKEN
            value: "$(cat ${SERVICEACCOUNT}/token)"
          - name: CACERT
            value: "${SERVICEACCOUNT}/ca.crt"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
      serviceAccountName: query-api
      serviceAccount: query-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
