kind: Deployment
apiVersion: apps/v1
metadata:
  name: query-api  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: query-api
        deploymentconfig: query-api
      annotations:
    spec:
      containers:
        - name: query-api
          image: registry.access.redhat.com/ubi8/ubi-minimal:8.8-1014
          command:
          - /bin/sh
          - -c
          - /getnumberofworkers
      volumes:
      - name: getnumberofworkers
        configMap:
          name: getnumberofworkres
          defaultMode: 755
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
      serviceAccountName: query-api
      serviceAccount: query-api
      volumeMounts:
      - name: getnumberofworkers
        mountPath: /tmp/getnumberofworkers
        subPath: getnumberofworkers
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
