apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: query-api
  namespace: query-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: query-api
  namespace: query-api
